# Generated by Django 4.0.1 on 2022-03-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='subtotal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
