# Generated by Django 4.0.1 on 2022-03-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_order_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
