# Generated by Django 4.0.1 on 2022-02-05 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='wishlist',
        ),
    ]
