# Generated by Django 4.0.1 on 2022-03-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
