# Generated by Django 4.0.1 on 2022-03-06 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
