# Generated by Django 4.0.1 on 2022-03-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Vendor',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
