# Generated by Django 4.0.1 on 2022-03-08 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Vendor',
            new_name='Vendor_name',
        ),
    ]
