# Generated by Django 4.0.1 on 2022-03-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_vendor_product_vendor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
